{% set name = "prometheus-fastapi-instrumentator" %}
{% set version = "5.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prometheus-fastapi-instrumentator-{{ version }}.tar.gz
  sha256: f1fa362043b974d138f5245acc973c32d1fa798bd2bd98ef2754befbf385a566

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
    - toml
  run:
    - fastapi >=0.38.1,<1.0.0
    - prometheus_client >=0.8.0,<1.0.0
    - python >=3.6,<4.0

test:
  imports:
    - prometheus_fastapi_instrumentator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trallnag/prometheus-fastapi-instrumentator
  summary: Instrument your FastAPI with Prometheus metrics
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
