{% set name = "prometheus-fastapi-instrumentator" %}
{% set version = "7.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prometheus_fastapi_instrumentator-{{ version }}.tar.gz
  sha256: be7cd61eeea4e5912aeccb4261c6631b3f227d8924542d79eaf5af3f439cbe5e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - starlette <1.0.0,>=0.30.0
    - prometheus_client <1.0.0,>=0.8.0

test:
  imports:
    - prometheus_fastapi_instrumentator
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/trallnag/prometheus-fastapi-instrumentator
  summary: Instrument your FastAPI with Prometheus metrics.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - lsetiawan
